// Generated by CoffeeScript 1.8.0

/*
Represents the root of the CSS AST.
 */
var Literal, Property, Rule, StyleSheet;

StyleSheet = (function() {
  function StyleSheet(rules) {
    this.rules = rules;
  }

  StyleSheet.prototype.toCSS = function() {
    return this.rules.map(function(rule) {
      return rule.toCSS();
    }).join("\n");
  };

  StyleSheet.prototype.rash = function() {
    return this;
  };

  return StyleSheet;

})();


/*
 */

Rule = (function() {
  function Rule(selector, properties) {
    this.selector = selector;
    this.properties = properties;
  }

  Rule.prototype.toCSS = function() {
    var properties;
    properties = this.properties.map(function(property) {
      return property.toCSS();
    }).join(";");
    return "" + this.selector + " {" + properties + "}";
  };

  return Rule;

})();


/*
 */

Property = (function() {
  function Property(name, values) {
    this.name = name;
    this.values = values;
  }

  Property.prototype.toCSS = function() {
    var values;
    values = this.values.map(function(value) {
      return value.toCSS();
    }).join(" ");
    return "" + this.name + ": " + values;
  };

  return Property;

})();


/*
 */

Literal = (function() {
  function Literal(value) {
    this.value = value;
  }

  Literal.prototype.toCSS = function() {
    return this.value;
  };

  return Literal;

})();

exports.StyleSheet = StyleSheet;

exports.Rule = Rule;

exports.Property = Property;

exports.Literal = Literal;
