// Generated by CoffeeScript 1.8.0
var Rule, StyleSheet;

StyleSheet = (function() {
  function StyleSheet() {}

  return StyleSheet;

})();

Rule = (function() {
  function Rule() {}

  return Rule;

})();
